site_name: My Docs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_css:
    # - https://cdn.jsdelivr.net/npm/katex@0.16.2/dist/katex.min.css

extra_javascript:
    # - https://cdn.jsdelivr.net/npm/katex@0.16.2/dist/katex.min.js
    # - https://cdn.jsdelivr.net/npm/katex@0.16.2/dist/contrib/auto-render.min.js
    # - js/katex.js
  # - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
